# Generated by Django 4.1.5 on 2023-11-29 15:24

from django.db import migrations
import src.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.users.models.UserManager()),
            ],
        ),
    ]
