# Generated by Django 4.1.5 on 2023-11-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
